name: custom-workflow

on:
  # `workflow_call` makes this workflow callable from other workflows
  workflow_call:
    # parameters that should be passed to the workflow
    inputs:
      message-to-print:
        description: "A message that will be printed in the workflow"
        required: true
        type: string
    
    # secrets that should be passed to the workflow
    # if calling workflow uses 'inherit' to import secret then we can reference them directly in workflow without defining them here
    secrets:    
      # Remember that "Secret names can only contain alphanumeric characters ([a-z], [A-Z], [0-9]) or underscores (_). Spaces are not allowed. Must start with a letter ([a-z], [A-Z]) or underscores (_)."
      secret_to_hide: 
        description: "A secret that will be passed to the workflow"
        required: true
    
    # and we can output some values from the workflow
    outputs:
      workflow-output:
        description: "The first output string"
        value: ${{ jobs.emit-output.outputs.output-from-job }}

jobs: 
  print-message:
    runs-on: ubuntu-latest
    steps: 
      # we don't need to checkout repo but I just leave it here for demonstration
      - name: checkout repo
        uses: actions/checkout@v3

      - name: print message
        run: echo "${{ inputs.message-to-print }}"
                  
  test-secret:     
    runs-on: ubuntu-latest
    steps:                 
      - run: |
          if [ "${{ secrets.secret_to_hide }}" == "MY SECRET MESSAGE" ]; then
            echo "Secret is good"
          else
            echo "Secret is not correct"
          fi
            echo 

  emit-output:
    runs-on: ubuntu-latest
    # it requires some gymnastics to pass outputs from one job to another
    outputs:
      # notice that `greeting` is an ID of step were we take output from
      # output-var-name - is a variable name where we store output 
      output-from-job: ${{ steps.greeting.outputs.output-var-name }}
    steps:
      - name: Greeting step        
        id: greeting
        run: echo "output-var-name=Hi, I'm Reusable Workflow" >> $GITHUB_OUTPUT
      